config/routes.rb
Rails.application.routes.draw do
  resources :productos do
    collection do 
      get :impr
      get :imprpdf
    end 
  
  end
  resources :tipos

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :tipo
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/productos_controller.rb
require './app/reportes/productos_csv.rb'
require './app/reportes/productos_pdf.rb'
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]
  # respond_to :html, :json, :csv 

  def index
    @productos = Producto.all


  end

  def show
  end

  def new
    @producto = Producto.new
  end

  def edit
  end

  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: "El producto fue creado con éxito." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: "El producto fue actualizado con éxio." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: "El producto fue eliminado con éxito." }
      format.json { head :no_content }
    end
  end  

  
  def impr
    send_data ProductoReporte.new.call,
    :type => 'text/csv; charset=iso-8859-1; header=present', 
    :disposition=>'attachment; filename=iprm.csv'
  end 

  def imprpdf
    pdf = ProductosPdf.new.call
    send_data pdf.render, :type => 'application/pdf', :disposition => 'inline', :filename => 'test.pdf'
  end

  private
  
  def set_producto
    @producto = Producto.find(params[:id])
  end

  def producto_params
    params.require(:producto).permit(:name, :descripcion, :precio, :tipo_id )
  end


end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: %i[ show edit update destroy ]

  def index
    @tipos = Tipo.all
  end

  def show
  end

  def new
    @tipo = Tipo.new
  end

  def edit
  end

  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: "El tipo de producto fue creado con éxito." }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tipos.update(tipo_params)
        format.html { redirect_to @tipos, notice: "El tipo producto fue actualizado con éxio." }
        format.json { render :show, status: :ok, location: @tipos }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tipos.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: "El producto fue eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_tipo
      @tipos = Tipo.find(params[:id])
    end

    def tipo_params
      params.require(:tipo).permit(:tipo, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> este porducto no se puede guardar:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <%= form.collection_select :tipo_id, Tipo.all, :id, :tipo %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Atras', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<%= link_to 'nuevo tipo de producto', tipos_path %>
<br></br>
<%= link_to 'nuevo producto', new_producto_path %>
<br></br>
<%= link_to "CVS", {:action => 'impr'} %>
<br></br>
<%= link_to "PDP", {:action => 'imprpdf'} %>


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Tipo de Producto<th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.name %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.tipo.tipo%></td>
        <td><%= link_to 'Mostrar', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Borrar', producto, method: :delete, data: { confirm: 'estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Atras', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>tipo de producto:</strong>
  <%= @producto.tipo %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Atras', productos_path %>

app/views/tipos/_form.html.erb
<%= form_with(model: tipo) do |form| %>
  <% if tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo.errors.count, "error") %> este tipo porducto no se puede guardar:</h2>

      <ul>
        <% tipo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editar Tipo de Producto</h1>

<%= render 'form', tipo: @tipos %>

<%= link_to 'mostrar', @tipo %> |
<%= link_to 'atras', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo de Productos</h1>

<%= link_to 'Regresar a la tabla productos', productos_path %>

<br></br>

<%= link_to 'nuevo tipo producto', new_tipo_path %>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.tipo %></td>
        <td><%= tipo.descripcion %></td>
        <td><%= link_to 'mostrar', tipo %></td>
        <td><%= link_to 'Editar', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Borrar', tipo, method: :delete, data: { confirm: 'estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tipos/new.html.erb
<h1>New Tipo Producto</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Atras', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>tipo:</strong>
  <%= @tipos.tipo.tipo%>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipos.descripcion %>
</p>


<%= link_to 'Editar', edit_tipo_path(@tipos) %> |
<%= link_to 'Atras', tipos_path %>